config/routes.rb
Rails.application.routes.draw do
  root :to=>"inicio#inicio"
  scope "(:locale)", locale: /es|en/ do
    resources :usuarios
    resources :lista_ejercitos
    resources :equipo_disponibles
    resources :reglas_especiales
    resources :equipos
    resources :heros
    resources :tropas
    resources :ejercitos
    resources :application

    get "login" => "usuarios#logueo"
    get "signed_out" => "usuarios#signed_out"
    post "login" => "usuarios#login"
  end

end

app/models/hero.rb
class Hero < ActiveRecord::Base
  belongs_to :ejercito
  has_and_belongs_to_many :reglas_especiale
  has_and_belongs_to_many :lista_ejercito
  has_and_belongs_to_many :equipo_disponible

  def ejercito
    ejercito = Ejercito.find(self.ejercito_id)
    ejercito.nombre
  end

end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user
  before_filter :denied_access, :only => [:destroy]

  # GET /heros
  # GET /heros.json
  def index
#    @heros = Hero.all

    if params[:name].present? || params[:ejercito].present?
      scope = Hero.all
      scope = scope.where("nombre like '%#{params[:name]}%'") if params[:name].present?
      scope = scope.where("ejercito_id = #{params[:ejercito]}") if params[:ejercito].present?
      scope = scope.order('ejercito_id asc').paginate(page: params[:page], per_page: 15)
      @heros = scope
    else
      @heros = Hero.order('ejercito_id asc').paginate(page: params[:page], per_page: 15)
    end
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
    @equipo_disponible = Equipo.find_by_sql("select e.nombre, e.descripcion, e.puntos from equipos e, equipo_disponibles ed, heroes_equipo_disponible hed, heros h
                                              where e.id = ed.equipo_id
                                                and ed.tipo_miniatura = 'Hero'
                                                and ed.id = hed.equipo_disponible_id
                                                and hed.heroe_id = h.id
                                                and h.id = #{@hero.id}")
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: "#{t 'heros.index.mensaje_nuevo_ok' }" }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: "#{t 'heros.index.mensaje_actualizo_ok' }" }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:nombre, :puntos, :combate, :impacto, :fuerza, :defensa, :ataque, :herida, :valor, :p_poder, :p_voluntad, :p_destino, :descripcion, :ejercito_id)
    end
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/views/heros/_form.html.erb
<div class="container">
  <div class="row">
    <div class="well">
      <div class="media">
        <div class="media-body">
          <%= form_for(@hero, :html => {:class => 'col-md-10 col-md-offset-1 form-horizontal form-inline', :role => 'form'}) do |f| %>
              <% if @hero.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

                    <ul>
                      <% @hero.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
              <% end %>
              <fieldset>
                <legend>
                  <div class="col-md-12">
                    <div class="col-md-9" style="padding-left: 0%"><%= t 'heros.show.fieldset_info_general' %></div>
                    <div class="col-md-3">
                      <%= link_to @hero, :class => "btn-lg" do %>
                          <i class="glyphicon glyphicon-eye-open"></i>
                      <% end %> |
                      <%= link_to heros_path, :class => "btn-lg" do %>
                          <i class="glyphicon glyphicon-chevron-left"><%= t 'common.atras' %></i>
                      <% end %>

                    </div>
                  </div>
                </legend>
                <div class="row">
                  <div class="col-md-12">
                    <div class="input-group col-md-7">
                      <%= f.text_field :nombre, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_nombre' %></span>
                    </div>
                    <div class="input-group col-md-3 col-md-offset-1">
                      <%= f.number_field :puntos, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_puntos' %></span>
                    </div>
                  </div>
                </div>
              </fieldset>
              <br/>
              <fieldset>
                <legend><div class="col-md-9"><%= t 'heros.show.fieldset_atributos' %></div></legend>
                <div class="row">
                  <div class="col-md-12">
                    <div class="input-group col-md-3">
                      <%= f.number_field :combate, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_combate' %></span>
                    </div>
                    <div class="input-group col-md-3 col-md-offset-1">
                      <%= f.text_field :impacto, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_impacto' %></span>
                    </div>
                    <div class="input-group col-md-3 col-md-offset-1">
                      <%= f.number_field :fuerza, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_fuerza' %></span>
                    </div>
                  </div>

                </div>
                <br/>

                <div class="row">
                  <div class="col-md-12">

                    <div class="input-group col-md-3">
                      <%= f.number_field :herida, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_herida' %></span>
                    </div>

                    <div class="input-group col-md-3 col-md-offset-1">
                      <%= f.number_field :defensa, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_defensa' %></span>
                    </div>

                    <div class="input-group col-md-3 col-md-offset-1">
                      <%= f.number_field :ataque, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_ataque' %></span>
                    </div>
                  </div>
                </div>
                <br/>

                <div class="row">
                  <div class="col-md-12">

                    <div class="input-group col-md-3 ">
                      <%= f.number_field :valor, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_valor' %></span>
                    </div>

                    <div class="input-group col-md-7 col-md-offset-1">
                      <%= f.select :ejercito_id, options_from_collection_for_select(Ejercito.all, :id, :nombre, @hero.ejercito_id), {:include_blank => true}, {:class => 'form-control'} %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_ejercito' %></span>
                    </div>
                  </div>
                </div>
                <br/>

                <div class="row">
                  <div class="col-md-12">
                    <div class="input-group col-md-3">
                      <%= f.number_field :p_poder, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_p_poder' %></span>
                    </div>

                    <div class="input-group  col-md-3 col-md-offset-1">
                      <%= f.number_field :p_voluntad, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_p_voluntad' %></span>
                    </div>

                    <div class="input-group  col-md-3 col-md-offset-1">
                      <%= f.number_field :p_destino, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_p_destino' %></span>
                    </div>
                  </div>
                </div>
              </fieldset>
              <br/>
              <fieldset>
                <legend><div class="col-md-9"><%= t 'heros.show.fieldset_otros' %></div></legend>
                <div class="row">
                  <div class="col-md-12">
                    <div class="input-group col-md-12">
                      <%= f.text_area :descripcion, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'heros.index.campo_descripcion' %></span>
                    </div>
                  </div>
                </div>
                <br/>

                <div class="actions">
                  <%= f.submit "#{t 'heros.index.actualizar_heroe'}", :class => 'btn btn-default', :style => 'width:100%; background-image: linear-gradient(to bottom, #FFF 0px, #E0E0E0 100%); background-repeat: repeat-x;' %>
                </div>
              </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/heros/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-4 col-md-offset-4 text-center" style="float: left">
      <h2><%= t '.titulo_editar_heroes' %></h2>
    </div>
  </div>
  <br />
<%= render 'form' %>

</div>

app/views/heros/index.html.erb
<style>
    .input-group[class*="col-"] {
        float: left;
    }
</style>
<div class="container">
  <div class="row">
    <p id="notice"><%= notice %></p>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-8">
        <h1><%= t '.titulo_lista_heroes' %></h1>
      </div>
      <div class="col-md-4">
        <div class="col-md-6 col-md-offset-1">
          <%= link_to new_hero_path, :class => 'btn btn-sm btn-default ' do %>
              <i class="glyphicon glyphicon-plus">
                <%= t '.nuevo_heroe' %>
              </i>
          <% end %>
        </div>
        <div class="col-md-4 col-md-offset-1">
          <%= link_to root_path, :class => "btn btn-sm btn-default" do %>
              <i class="glyphicon glyphicon-chevron-left"><%= t 'common.atras' %></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="pull-left col-md-12">

      <%= form_tag({:controller => "heros", :action => "index"}, :method => :get, :id => "query_form") do %>

          <div class="media">
            <div class="media-body">
              <fieldset>
                <div class="row">
                  <legend>
                    <div class="col-md-9"><%= t 'tropas.index.buscador' %></div>
                  </legend>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <div class="input-group col-md-5">
                      <%= text_field_tag(:name, params[:name], :autocomplete => "off", :class => "form-control", :placeholder => "#{t 'tropas.index.buscador'}") %>
                      <span class="input-group-addon"><%= t 'tropas.index.campo_nombre' %></span>
                    </div>

                    <div class="input-group col-md-5 col-md-offset-2">
                      <%= select_tag :ejercito, options_from_collection_for_select(Ejercito.all, :id, :nombre), {:include_blank => true, :class => 'form-control'} %>
                      <span class="input-group-addon"><%= t 'tropas.index.campo_ejercito' %></span>
                    </div>

                  </div>
                </div>
                <br/>

                <div class="input-group col-md-2 ">
                  <%= submit_tag "Buscar", :class => "btn btn-default" %>
                </div>
              </fieldset>
            </div>
          </div>
      <% end %>

    </div>
  </div>
  <hr/>

  <div class="row">
    <table class="table table-responsive table-striped">
      <thead>
      <tr>
        <th><%= t '.campo_nombre' %></th>
        <th><%= t '.campo_puntos' %></th>
        <th><%= t '.campo_combate' %></th>
        <th><%= t '.campo_impacto' %></th>
        <th><%= t '.campo_fuerza' %></th>
        <th><%= t '.campo_defensa' %></th>
        <th><%= t '.campo_ataque' %></th>
        <th><%= t '.campo_herida' %></th>
        <th><%= t '.campo_valor' %></th>
        <th><%= t '.campo_p_poder' %></th>
        <th><%= t '.campo_p_voluntad' %></th>
        <th><%= t '.campo_p_destino' %></th>
        <th><%= t '.campo_ejercito' %></th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @heros.each do |hero| %>
          <tr>
            <td><%= hero.nombre %></td>
            <td><%= hero.puntos %></td>
            <td><%= hero.combate %></td>
            <td><%= hero.impacto %></td>
            <td><%= hero.fuerza %></td>
            <td><%= hero.defensa %></td>
            <td><%= hero.ataque %></td>
            <td><%= hero.herida %></td>
            <td><%= hero.valor %></td>
            <td><%= hero.p_poder %></td>
            <td><%= hero.p_voluntad %></td>
            <td><%= hero.p_destino %></td>
            <td><%= hero.ejercito %></td>
            <td><%= link_to hero do %>
                  <i class="glyphicon glyphicon-eye-open"></i>
              <% end %>
            </td>
            <td><%= link_to edit_hero_path(hero) do %>
                  <i class="glyphicon glyphicon-pencil"></i>
              <% end %>
            </td>
            <td><%= link_to hero, method: :delete, data: {confirm: "#{t '.confirmacion' }"} do %>
              <i class="glyphicon glyphicon-remove"></i>
      <% end %>
      </td>
      </tr>
      <% end %>
      </tbody>
    </table>
    <div class="row pull-right">
      <%= will_paginate @heros, :inner_window => 1 %>
    </div>
  </div>
</div>


<br>

app/views/heros/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-4 col-md-offset-4 text-center" style="float: left">
      <h2><%= t '.titulo_nuevo_heroe' %></h2>
    </div>
  </div>
  <br/>

<%= render 'form' %>
</div>

app/views/heros/show.html.erb
<div class="container">
  <div class="row">
  </div>
  <div class="row">
    <div class="well">
      <div class="media">
        <div class="media-body">
          <div style="float: left">
            <h4 class="media-heading">
              <b><%= @hero.nombre %>: <%= @hero.puntos %> <%= t '.campo_puntos' %></b>
            </h4>
          </div>
          <div style="float: right">
            <%= link_to edit_hero_path(@hero) do %>
                <i class="glyphicon glyphicon-pencil"></i>
            <% end %> |
            <%= link_to heros_path do %>
                <i class="glyphicon glyphicon-chevron-left"><%= t 'common.atras' %></i>
            <% end %>
          </div>
          <hr/>
          <div class="row">
            <div class="col-md-1 texto_centrado">
              <strong><%= t 'heros.index.campo_combate' %></strong><br/>
              <%= @hero.combate %>
            </div>

            <div class="col-md-1 texto_centrado">
              <strong><%= t 'heros.index.campo_impacto' %></strong><br/>
              <%= @hero.impacto %>
            </div>

            <div class="col-md-1 texto_centrado">
              <strong><%= t 'heros.index.campo_fuerza' %></strong>
              <br/>
              <%= @hero.fuerza %>
            </div>

            <div class="col-md-1 texto_centrado"><strong><%= t 'heros.index.campo_defensa' %></strong>
              <br/>
              <%= @hero.defensa %>
            </div>

            <div class="col-md-1 texto_centrado">
              <strong><%= t 'heros.index.campo_ataque' %></strong>
              <br/>
              <%= @hero.ataque %>
            </div>

            <div class="col-md-1 texto_centrado">
              <strong><%= t 'heros.index.campo_herida' %></strong>
              <br/>
              <%= @hero.herida %>
            </div>

            <div class="col-md-1 texto_centrado"><strong><%= t 'heros.index.campo_valor' %></strong>
              <br/>
              <%= @hero.valor %>
            </div>

            <div class="col-md-1 texto_centrado">
              <strong><%= t '.campo_p_poder' %></strong>
              <br/>
              <%= @hero.p_poder %>
            </div>

            <div class="col-md-1 texto_centrado" style="white-space: nowrap;">
              <strong><%= t '.campo_p_voluntad' %></strong>
              <br/>
              <%= @hero.p_voluntad %>
            </div>

            <div class="col-md-1 texto_centrado" style="white-space: nowrap;">
              <strong><%= t '.campo_p_destino' %></strong>
              <br/>
              <%= @hero.p_destino %>
            </div>

          </div>
          <hr/>
          <div class="row">
            <div class="col-md-12">
              <%= @hero.descripcion %>
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-md-12">
              <fieldset>
                <legend><%= t '.fieldset_equipo_disponible' %></legend>
                <ul>
                  <% @equipo_disponible.each do |ed| %>
                      <li><%= ed.nombre %>:<%= t('equipos.show.campo_puntos', count: ed.puntos.to_i ) %>  <%= ed.descripcion %></li>
                  <% end %>
                </ul>
              </fieldset>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>