config/routes.rb
Rails.application.routes.draw do
  root :to=>"inicio#inicio"
  scope "(:locale)", locale: /es|en/ do
    resources :usuarios
    resources :lista_ejercitos
    resources :equipo_disponibles
    resources :reglas_especiales
    resources :equipos
    resources :heros
    resources :tropas
    resources :ejercitos
    resources :application

    get "login" => "usuarios#logueo"
    get "signed_out" => "usuarios#signed_out"
    post "login" => "usuarios#login"
  end

end

app/models/ejercito.rb
class Ejercito < ActiveRecord::Base

  has_many :tropa
  has_many :hero
  validates_presence_of :nombre


end

app/controllers/ejercitos_controller.rb
class EjercitosController < ApplicationController
  before_action :set_ejercito, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user
  before_filter :denied_access, :only => [:destroy, :new, :create]

  # GET /ejercitos
  # GET /ejercitos.json
  def index
    @ejercitos = Ejercito.all
  end

  # GET /ejercitos/1
  # GET /ejercitos/1.json
  def show
  end

  # GET /ejercitos/new
  def new
    @ejercito = Ejercito.new
  end

  # GET /ejercitos/1/edit
  def edit
  end

  # POST /ejercitos
  # POST /ejercitos.json
  def create
    @ejercito = Ejercito.new(ejercito_params)

    respond_to do |format|
      if @ejercito.save
        format.html { redirect_to @ejercito, notice: "#{t 'ejercitos.index.mensaje_nuevo_ok' }"}
        format.json { render :show, status: :created, location: @ejercito }
      else
        format.html { render :new }
        format.json { render json: @ejercito.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ejercitos/1
  # PATCH/PUT /ejercitos/1.json
  def update
    respond_to do |format|
      if @ejercito.update(ejercito_params)
        format.html { redirect_to @ejercito, notice: "#{t 'ejercitos.index.mensaje_actualizo_ok' }" }
        format.json { render :show, status: :ok, location: @ejercito }
      else
        format.html { render :edit }
        format.json { render json: @ejercito.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ejercitos/1
  # DELETE /ejercitos/1.json
  def destroy
    @ejercito.destroy
    respond_to do |format|
      format.html { redirect_to ejercitos_url, notice: 'Ejercito was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ejercito
      @ejercito = Ejercito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ejercito_params
      params.require(:ejercito).permit(:nombre, :descripcion)
    end
end

app/helpers/ejercitos_helper.rb
module EjercitosHelper
end

app/views/ejercitos/_form.html.erb
<div class="container">
  <div class="row">
    <div class="well">
      <div class="media">
        <div class="media-body">
          <%= form_for(@ejercito, :html => {:class => 'col-md-10 col-md-offset-1 form-horizontal form-inline', :role => 'form'}) do |f| %>
              <% if @ejercito.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@ejercito.errors.count, "error") %> prohibited this ejercito from being
                      saved:</h2>

                    <ul>
                      <% @ejercito.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
              <% end %>
              <fieldset>
                <legend>
                  <div class="col-md-12">
                    <div class="col-md-9" style="padding-left: 0%"><%= t 'ejercitos.edit.fieldset_info_general' %></div>
                    <div class="col-md-3">
                      <%= link_to @ejercito, :class => "btn-lg" do %>
                          <i class="glyphicon glyphicon-eye-open"></i>
                      <% end %> |
                      <%= link_to ejercitos_path, :class => "btn-lg" do %>
                          <i class="glyphicon glyphicon-chevron-left"><%= t 'common.atras' %></i>
                      <% end %>

                    </div>
                  </div>
                </legend>
                <div class="row">
                  <div class="col-md-12">
                    <div class="input-group col-md-12">
                      <%= f.text_field :nombre, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'ejercitos.index.campo_nombre' %></span>
                    </div>
                  </div>
                </div>
                <br/>

                <div class="row">
                  <div class="col-md-12">
                    <div class="input-group col-md-12">
                      <%= f.text_area :descripcion, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'ejercitos.index.campo_descripcion' %></span>
                    </div>

                  </div>
                </div>
                <br/>

                <div class="actions">
                  <%= f.submit "#{t 'ejercitos.edit.actualizar_ejercito'}", :class => 'btn btn-default', :style => 'width:100%; background-image: linear-gradient(to bottom, #FFF 0px, #E0E0E0 100%);
background-repeat: repeat-x;' %>
                </div>
              </fieldset>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/ejercitos/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-4 col-md-offset-4 text-center" style="float: left">
      <h2><%= t '.titulo_editar_ejercito' %></h2>
    </div>
  </div>
  <br/>
  <%= render 'form' %>
</div>

app/views/ejercitos/index.html.erb
<div class="container">
  <div class="row">
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="col-md-8">
        <h1><%= t '.titulo_lista_ejercito' %></h1>
      </div>
      <div class="col-md-4">
        <div class="col-md-6 col-md-offset-1">
          <%= link_to new_ejercito_path, :class => 'btn btn-sm btn-default ' do %>
              <i class="glyphicon glyphicon-plus">
                <%= t 'tropas.index.nueva_tropa' %>
              </i>
          <% end %>
        </div>
        <div class="col-md-4 col-md-offset-1">
          <%= link_to root_path, :class => "btn btn-sm btn-default" do %>
              <i class="glyphicon glyphicon-chevron-left"><%= t 'common.atras' %></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <table class="table table-responsive table-striped">
      <thead>
      <tr>
        <th><%= t '.campo_nombre' %></th>
        <th colspan="3"><%= t 'common.acciones' %></th>
      </tr>
      </thead>

      <tbody>
      <% @ejercitos.each do |ejercito| %>
          <tr>
            <td><%= ejercito.nombre %></td>
            <td><%= link_to ejercito do %>
                  <i class="glyphicon glyphicon-eye-open"></i>
              <% end %>
            </td>
            <td><%= link_to edit_ejercito_path(ejercito) do %>
                  <i class="glyphicon glyphicon-pencil"></i>
              <% end %>
            </td>
            <td><%= link_to ejercito, method: :delete, data: {confirm: "#{t '.confirmacion' }"} do %>
              <i class="glyphicon glyphicon-remove"></i>
      <% end %>
      </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/ejercitos/new.html.erb
<h1>New Ejercito</h1>

<%= render 'form' %>

<%= link_to 'Back', ejercitos_path %>

app/views/ejercitos/show.html.erb
<div class="container">
  <div class="row">
  </div>
  <div class="row">
    <div class="well">
      <div class="media">
        <div class="media-body">

          <div style="float: left">
            <h4 class="media-heading">
              <%= @ejercito.nombre %>
            </h4>
          </div>
          <div style="float: right">
            <%= link_to edit_ejercito_path(@ejercito) do %>
                <i class="glyphicon glyphicon-pencil"></i>
            <% end %> |
            <%= link_to ejercitos_path do %>
                <i class="glyphicon glyphicon-chevron-left"><%= t 'common.atras' %></i>
            <% end %>
          </div>
          <hr/>
          <p>
            <%= @ejercito.descripcion %>
          </p>


        </div>
      </div>
    </div>
  </div>
</div>