config/routes.rb
Rails.application.routes.draw do
  root :to=>"inicio#inicio"
  scope "(:locale)", locale: /es|en/ do
    resources :usuarios
    resources :lista_ejercitos
    resources :equipo_disponibles
    resources :reglas_especiales
    resources :equipos
    resources :heros
    resources :tropas
    resources :ejercitos
    resources :application

    get "login" => "usuarios#logueo"
    get "signed_out" => "usuarios#signed_out"
    post "login" => "usuarios#login"
  end

end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
end

app/views/inicio/inicio.html.erb
<style>
  .col-md-6 {
      padding-right: 0px;
      padding-left: 0px;
  }
  .min {
    width: 100%;
  }
</style>
<% if current_user %>
    <div class="row col-md-offset-5" style="padding-bottom: 5%;">
        <h1><%= t '.bienvenido' %></h1>
    </div>
    <div class="row">
      <div class="col-md-3">
        <img src="../images/escudo_elfo.png" />
      </div>
      <div class="panel panel-info col-md-6">
        <div class="panel-heading"><%= t '.titulo_panel_inicio' %></div>
        <div class="panel-body">
          <div class="btn-group col-md-12">
            <div class="row">
                <div class="col-md-4">
                    <%= link_to ejercitos_path, class: "btn btn-default min" do %>
                        <img src="../images/ejercitos.png"/><br />
                        <%= t 'ejercitos.index.titulo_lista_ejercito' %>
                    <% end %>
                </div>
                <div class="col-md-4">
                    <%= link_to tropas_path, class: "btn btn-default min" do %>
                        <img src="../images/tropas.png" /><br />
                        <%= t 'tropas.index.titulo_lista_tropas' %>
                    <% end %>
                </div>
                <div class="col-md-4">
                  <%= link_to heros_path, class: "btn btn-default min" do %>
                      <img src="../images/heroes.png" /><br />
                      <%= t 'heros.index.titulo_lista_heroes' %>
                  <% end %>
                </div>
          </div>
            <div class="row" style="padding-top: 5%">
              <div class="col-md-4 ">
                <%= link_to equipos_path, class: "btn btn-default min" do %>
                    <img src="../images/equipos.png" /><br />
                    <%= t 'equipos.index.titulo_lista_equipo' %>
                <% end %>
              </div>

              <div class="col-md-4 ">
                <%= link_to reglas_especiales_path, class: "btn btn-default min" do %>
                    <img src="../images/reglas.png" /><br />
                    <%= t 'reglas_especiales.index.titulo_lista_reglas_especiales' %>
                <% end %>
              </div>

              <div class="col-md-4 ">
                <%= link_to lista_ejercitos_path, class: "btn btn-default min" do %>
                    <img src="../images/lista_ejercitos.png" /><br />
                    <%= t 'lista_ejercitos.index.titulo_lista_lista_ejercitos' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-2 col-md-offset-1">
      <img src="../images/escudo_gondor.png" />
      </div>

    </div>
<% else %>
    <div class="row" style="margin-top: 15%">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">

          <div class="panel-heading">
            <h3 class="panel-title"><strong><%= t '.titulo_login' %> <img src="../images/casco_de_sauron.png" width="15%" style="float:right; margin: -10%"/></strong></h3>

          </div>
          <div class="panel-body">

            <%= form_tag :controller => 'usuarios', :action => 'login', :method => 'get', :class => 'form' do %>
                <div class="form-group">
                    <%= label_tag t '.usuario' %><br />
                    <%= text_field_tag 'usuario', params[:usuario], class: 'form-control' %>
                </div>
                <div class="form-group">
                  <%= label_tag t '.password' %><br />
                  <%= password_field_tag 'password', params[:password], class: 'form-control' %>
                </div>
                <div class="col-md-offset-3">
                  <button type="submit" class="btn btn-sm btn-success"><%= t '.login' %></button>&nbsp;&nbsp;&nbsp;
                  <button type="reset" class="btn btn-sm btn-default col-md-offset-2"><%= t '.limpiar_form' %></button>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>