config/routes.rb
Rails.application.routes.draw do
  root :to=>"inicio#inicio"
  scope "(:locale)", locale: /es|en/ do
    resources :usuarios
    resources :lista_ejercitos
    resources :equipo_disponibles
    resources :reglas_especiales
    resources :equipos
    resources :heros
    resources :tropas
    resources :ejercitos
    resources :application

    get "login" => "usuarios#logueo"
    get "signed_out" => "usuarios#signed_out"
    post "login" => "usuarios#login"
  end

end

app/models/equipo.rb
class Equipo < ActiveRecord::Base
  has_one :equipo_disponible

end

app/controllers/equipos_controller.rb
class EquiposController < ApplicationController
  before_action :set_equipo, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user
  before_filter :denied_access, :only => [:destroy, :new, :create]

  # GET /equipos
  # GET /equipos.json
  def index
    @equipos = Equipo.all
  end

  # GET /equipos/1
  # GET /equipos/1.json
  def show
  end

  # GET /equipos/new
  def new
    @equipo = Equipo.new
  end

  # GET /equipos/1/edit
  def edit
  end

  # POST /equipos
  # POST /equipos.json
  def create
    @equipo = Equipo.new(equipo_params)

    respond_to do |format|
      if @equipo.save
        format.html { redirect_to @equipo, notice: 'Equipo was successfully created.' }
        format.json { render :show, status: :created, location: @equipo }
      else
        format.html { render :new }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipos/1
  # PATCH/PUT /equipos/1.json
  def update
    respond_to do |format|
      if @equipo.update(equipo_params)
        format.html { redirect_to @equipo, notice: 'Equipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipo }
      else
        format.html { render :edit }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipos/1
  # DELETE /equipos/1.json
  def destroy
    @equipo.destroy
    respond_to do |format|
      format.html { redirect_to equipos_url, notice: 'Equipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipo
      @equipo = Equipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipo_params
      params.require(:equipo).permit(:nombre, :descripcion, :puntos)
    end
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/views/equipos/_form.html.erb
<div class="container">
  <div class="row">
    <div class="well">
      <div class="media">
        <div class="media-body">
          <%= form_for(@equipo, :html => {:class => 'col-md-10 col-md-offset-1 form-horizontal form-inline', :role => 'form'}) do |f| %>
              <% if @equipo.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@equipo.errors.count, "error") %> prohibited this equipo from being saved:</h2>

                    <ul>
                      <% @equipo.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
              <% end %>
              <fieldset>
                <legend>
                  <div class="col-md-12">
                    <div class="col-md-9" style="padding-left: 0%"><%= t 'equipos.edit.fieldset_info_general' %></div>
                    <div class="col-md-3">
                      <%= link_to @equipo, :class => "btn-lg" do %>
                          <i class="glyphicon glyphicon-eye-open"></i>
                      <% end %> |
                      <%= link_to equipos_path, :class => "btn-lg" do %>
                          <i class="glyphicon glyphicon-chevron-left"><%= t 'common.atras' %></i>
                      <% end %>

                    </div>
                  </div>
                </legend>
                <div class="row">
                  <div class="col-md-12">
                    <div class="input-group col-md-7">
                      <%= f.text_field :nombre, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'equipos.index.campo_nombre' %></span>
                    </div>

                    <div class="input-group col-md-3 col-md-offset-1">
                      <%= f.number_field :puntos, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'equipos.index.campo_puntos' %></span>
                    </div>
                  </div>
                </div>
              </fieldset>
              <br/>
              <fieldset>
                <legend>
                  <div class="col-md-9"><%= t 'equipos.edit.fieldset_otros' %></div>
                </legend>
                <div class="row">
                  <div class="col-md-12">
                    <div class="input-group col-md-12">
                      <%= f.text_area :descripcion, :class => 'form-control' %>
                      <span class="input-group-addon"><%= t 'equipos.index.campo_descripcion' %></span>
                    </div>
                  </div>
                </div>
                <br/>

                <div class="actions">
                  <%= f.submit "#{t 'reglas_especiales.index.actualizar_regla'}", :class => 'btn btn-default', :style => 'width:100%; background-image: linear-gradient(to bottom, #FFF 0px, #E0E0E0 100%);
    background-repeat: repeat-x;' %>
                </div>
              </fieldset>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/equipos/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-4 col-md-offset-4 text-center" style="float: left">
      <h2><%= t '.titulo_editar_equipo' %></h2>
    </div>
  </div>
  <br/>
  <%= render 'form' %>
</div>

app/views/equipos/index.html.erb
<div class="container">
  <div class="row">
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="col-md-8">

        <h1><%= t '.titulo_lista_equipo' %></h1>
      </div>
      <div class="col-md-4">
        <div class="col-md-6 col-md-offset-1">
          <%= link_to new_equipo_path, :class => 'btn btn-sm btn-default ' do %>
              <i class="glyphicon glyphicon-plus">
                <%= t '.nuevo_equipo' %>
              </i>
          <% end %>
        </div>
        <div class="col-md-4 col-md-offset-1">
          <%= link_to root_path, :class => "btn btn-sm btn-default" do %>
              <i class="glyphicon glyphicon-chevron-left"><%= t 'common.atras' %></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <table class="table table-responsive table-striped">
      <thead>
      <tr>
        <th><%= t '.campo_nombre' %></th>
        <th><%= t '.campo_descripcion' %></th>
        <th><%= t '.campo_puntos' %></th>
        <th colspan="3"><%= t 'common.acciones' %></th>
      </tr>
      </thead>

      <tbody>
      <% @equipos.each do |equipo| %>
          <tr>
            <td><%= equipo.nombre %></td>
            <td><%= equipo.descripcion %></td>
            <td><%= equipo.puntos %></td>
            <td><%= link_to equipo do %>
                  <i class="glyphicon glyphicon-eye-open"></i>
              <% end %>
            </td>
            <td><%= link_to edit_equipo_path(equipo) do %>
                  <i class="glyphicon glyphicon-pencil"></i>
              <% end %>
            </td>
            <td><%= link_to equipo, method: :delete, data: {confirm: "#{t '.confirmacion' }"} do %>
              <i class="glyphicon glyphicon-remove"></i>
      <% end %>
      </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/equipos/new.html.erb
<h1>New Equipo</h1>

<%= render 'form' %>

<%= link_to 'Back', equipos_path %>

app/views/equipos/show.html.erb
<div class="container">
  <div class="row">
  </div>
  <div class="row">
    <div class="well">
      <div class="media">
        <div class="media-body">

          <div style="float: left">
            <h4 class="media-heading">
              <b><%= @equipo.nombre %>: <%= t('.campo_puntos', count: @equipo.puntos.to_i ) %></b>
            </h4>
          </div>
          <div style="float: right">
            <%= link_to edit_equipo_path(@equipo) do %>
                <i class="glyphicon glyphicon-pencil"></i>
            <% end %> |
            <%= link_to equipos_path do %>
                <i class="glyphicon glyphicon-chevron-left"><%= t 'common.atras' %></i>
            <% end %>
          </div>
          <hr/>
          <p>
            <%= @equipo.descripcion %>
          </p>

        </div>
      </div>
    </div>
  </div>
</div>